name: easy_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.5.4

dependencies:
  clipboard: ^0.1.3
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  gpt_markdown: ^1.0.8
  http: ^1.3.0
  loading_animation_widget: ^1.3.0
  package_info_plus: ^8.2.1
  shared_preferences: ^2.5.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
